swagger: "2.0"
info:
  title: Path-Altering Reverse Proxy Example
  version: '1.0'
basePath: /swagger
paths:
  /hello:
    get:
      summary: say hi
      operationId: app.hello
      responses:
        '200':
          description: hello
          schema:
            type: string
